// src/sanity/schemaTypes/objects/seo.ts
import { defineType, defineField } from 'sanity';

/**
 * SEO metadata object.
 *
 * Used in:
 * - Pages
 * - Posts
 * - Destinations
 *
 * Notes for editors:
 * - All fields are optional.
 * - If left empty, sensible defaults will be generated by the frontend
 *   (page title, excerpt, or cover image).
 *
 * Philosophy:
 * - Keep SEO simple and intentional.
 * - Avoid keyword stuffing or duplicate values across pages.
 */

export default defineType({
  name: 'seo',
  title: 'SEO',
  type: 'object',

  fields: [
    /* ------------------------------------------------------------------- */
    /* Meta title                                                          */
    /* ------------------------------------------------------------------- */

    defineField({
      name: 'metaTitle',
      title: 'Meta title',
      type: 'string',
      description:
        'Optional override for the page title shown in search results. ' +
        'Recommended length: up to 60 characters. ' +
        'If empty, the page title will be used automatically.',
      validation: (r) => r.max(60),
    }),

    /* ------------------------------------------------------------------- */
    /* Meta description                                                    */
    /* ------------------------------------------------------------------- */

    defineField({
      name: 'metaDescription',
      title: 'Meta description',
      type: 'text',
      rows: 3,
      description:
        'Optional short summary for search engines. ' +
        'Recommended length: up to 160 characters. ' +
        'Write a clear, human-friendly sentence (not a list of keywords).',
      validation: (r) => r.max(160),
    }),

    /* ------------------------------------------------------------------- */
    /* Open Graph image                                                    */
    /* ------------------------------------------------------------------- */

    defineField({
      name: 'ogImage',
      title: 'Open Graph image',
      type: 'reference',
      to: [{ type: 'mediaItem' }],
      options: {
        filter: 'type == "image"',
      },
      description:
        'Optional image used when sharing this page on social platforms (WhatsApp, Twitter/X, Facebook). ' +
        'If not set, a default image will be used.',
    }),
  ],
});
