import type { Metadata } from "next";
// Root layout shared across all routes
import "./globals.css";
// Configure global fonts
import { Inter, Roboto_Mono } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
});

// Default site metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Wrap all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {/* Render global navigation */}
        <Navbar />
        {/* Render current route */}
        {children}
      </body>
    </html>
  );
}